In [13]:
import numpy as np
import cc3d
import numpy as np
from PIL import Image

src = '/home/pxl/myProject/血管分割/molong-resource/true_3044_e03e0573e1ea98fe3f48.png' # 480*480
src2 = '/home/pxl/myProject/血管分割/molong-resource/pred_3044_a1c1b64aade9f79e5c60.png'
src3 = '/home/pxl/myProject/血管分割/molong-resource/true.jpg'

def twod(src):
  img = Image.open(src)
  return np.array(img)[:,:,0]

# 假设你有一个二值图像
image = twod(src)
image2 = twod(src2)
image3 = twod(src3)

# 进行连通分量分析
# labels_out 是一个与输入图像相同维度的数组，每个连 通分量都会被赋予一个唯一的标签（整数值），代表它所属的连通分量。
# numcomp 是连通分量的总数，表示在图像中找到的连通分量的数量。

labels_out, numcomp = cc3d.connected_components(image, connectivity=8, return_N=True) # 26-connected
labels_out2, numcomp2 = cc3d.connected_components(image2, connectivity=8, return_N=True) # 26-connected
labels_out3, numcomp3 = cc3d.connected_components(image3, connectivity=8, return_N=True) # 26-connected

print(f"Number of connected components: {numcomp}")
print(f"Number of connected components: {numcomp2}")
print(f"Number of connected components: {numcomp3}")


print(labels_out)
np.savetxt('/home/pxl/myProject/血管分割/molong-resource/血管image.txt', labels_out, fmt='%d')


def calculate_critical_(labels_out, numcomp):
    # 计算每个连通分量的面积（或体积)
    unique_labels, counts = np.unique(labels_out, return_counts=True)

    # 定义一个阈值，小于该阈值的分量被视为潜在的拓扑失败点=
    threshold = 10  # 根据你的图像情况调整这个值
    potential_failure_points = unique_labels[counts < threshold]

    # 标记潜在的拓扑失败点
    failure_map = np.isin(labels_out, potential_failure_points)

    print(f"Potential topology failure points: {len(potential_failure_points)}")

    # 可视化或进一步处理 failure_map，例如高亮显示或统计失败点的分布

    # 扩展failure_map中为True的点周围的区域
    for i in range(failure_map.shape[0]):
        for j in range(failure_map.shape[1]):
            if failure_map[i][j]:
                for k in range(max(i-5, 0), min(i+6, failure_map.shape[0])):
                    for l in range(max(j-5, 0), min(j+6, failure_map.shape[1])):
                        failure_map[k][l] = True

    # 统计failure_map中为True的点的数量



Number of connected components: 4
Number of connected components: 218
Number of connected components: 39933
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
